### ISSUE TITLE
In file nvtt_samples/compress/compress.cpp std::path is used wrongly

### ISSUE THREAD

**Issue by ongamex** [nvpro-samples/nvtt_samples#1]
In file nvtt_samples/compress/compress.cpp std::path is used wrongly

See line 410
 output = input.replace_extension("dds");
 
replace_extension modifies the @input and as a result the program doesn't work with non-explicit output file:

Replacing the line with:
output = input;
output.replace_extension("dds");

fixes the issue

**Comment by NBickford-NV** [comment]
Thank you @ongamex for catching this! I believe I've fixed this and a few other instances where `replace_extension` was used in a similar incorrect way in https://github.com/nvpro-samples/nvtt_samples/commit/8c2f5016aecff8ab5142df336d3014d6159280e4.
